### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by chf0x** [rbran/sleigh-rs#11]
Hi! Thank you for the great library. I am curious, have you compared the performance between your implementation and the original one? If so, what were the results?

**Comment by rbran** [comment]
Hello, there are two original ones: one in java and other in c++. The result could also depend on what is being tested, if you are only compiling the sleigh file, disassembling bytes codes, or generating pcodes for each instruction, etc.

Although this project can compile a sleigh file very fast (~.17s for tricore) it's not ready yet to be benchmarked against the original implementations.
