### ISSUE TITLE
TakeLsbTooSmall in x86-64 sleigh.

### ISSUE THREAD

**Issue by akuseru** [rbran/sleigh-rs#13]
```
Table {
      location: File(
          FileSpan {
              start: FileLocation {
                  file: "/Applications/ghidra/Ghidra/Processors/x86/data/languages/ia.sinc",
                  line: 3225,
                  column: 0,
              },
              end_line: 3225,
              end_column: 1,
          },
      ),
      error: Execution(
          VarSize(
              AssignmentSides {
                  left: Value(
                      64,
                  ),
                  right: Value(
                      32,
                  ),
                  location: File(
                      FileSpan {
                          start: FileLocation {
                              file: "/Applications/ghidra/Ghidra/Processors/x86/data/languages/ia.sinc",
                              line: 1611,
                              column: 4,
                          },
                          end_line: 1611,
                          end_column: 5,
                      },
                  ),
                  backtrace: "sleigh-rs/src/semantic/inner/execution/assignment.rs:196",
              },
          ),
      ),
  }
  ```
  
  When processing x86-64 sleigh, I am encountering a `TakeLsbTooSmall` error. 
  
 I think this is because `pcRelSimm32` can be both 32 and 64 in size.  the problematic lines:

https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/x86/data/languages/ia.sinc#L1017-L1019

I am not sure what the best approach to resolve this is, otherwise I would include a pull request to fix it.  I haven't had a chance to track down how the parser in ghidra handles this case. 

If you have any recommendations for how this should be resolved, I can take a stab at fixing it.

**Comment by rbran** [comment]
Yes, that happen because the default sleigh implementation is very liberal with the field sizes, in this case the size is 0, like commented [here](https://github.com/NationalSecurityAgency/ghidra/blob/7dd38f2d95597c618af3d921f950fd6674805dd2/Ghidra/Processors/x86/data/languages/ia.sinc#L968).

I already solved this implementing a few hack, although I dislike how they are implemented, I think ghidra don't give me many options.

Thanks you for reporting, let me know if you are still having this problem.

**Comment by akuseru** [comment]
Awesome, these fixes seem to resolve all the parsing of the x86-64 sleigh I was having.
